### ISSUE TITLE
HOTD4c - 2 prompt appear

### ISSUE THREAD

**Issue by Trymado** [teknogods/teknoparrot-issues#100]
Please fill in the following information when creating a new issue:

**TeknoParrot version**: 
**Did this issue happen with an older version**: no
**Detailed description of issue**: After the latest Patreon update HOTD4c is displaying 2 prompts before loading. 
**Reproduction details**: Launch the game
**Pictures of issue**: http://www.emuline.org/uploads/monthly_2020_02/TKP.jpg.04ca698077fd90fc0cdf3ef9cdb84703.jpg

**Comment by Poliwrath** [comment]
Known issue, will probably be fixed within a few days.

**Comment by Trymado** [comment]
Great ! Thx
