### ISSUE TITLE
Rambo doesn't run on Teknoparrot

### ISSUE THREAD

**Issue by stevecrow85** [teknogods/teknoparrot-issues#101]
Hi, my pc is Acer Aspire VX 15 Intel (R) Core (TM) i7-7700HQ CPU @ 2.80GHz (8 CPUs), ~ 2.8GHz, 8 GB RAM with two video cards: one integrated Intel (R) HD Graphics 630 and one is a dedicated NVIDIA GeForce GTX 1050. I have the Teknoparrot emulator with the recommended components installed (DirectX 9 runtimes, Visual C ++ runtimes and for the Rambo game also Visual C ++ Redistributable Runtimes All-in-One). I am having problems starting the game. Since I'm a hardcore Rambo fan I would love to play it. Can you solve the problem for me? I created a video about it. Thank you in advance.

https://www.youtube.com/watch?v=B-VbA8Dpfjg&t=51s

**Comment by Poliwrath** [comment]
Thanks for the video. I'm assuming you installed the shader fix from the discord server?

Since you're on a laptop, you'll either have to set BudgieLoader to use NVIDIA card in the control panel, or always use the NVIDIA card. ("High-performance NVIDIA processor" or something)

**Comment by stevecrow85** [comment]
> Thanks for the video. I'm assuming you installed the shader fix from the discord server?
> 
> Since you're on a laptop, you'll either have to set BudgieLoader to use NVIDIA card in the control panel, or always use the NVIDIA card. ("High-performance NVIDIA processor" or something)

I installed as you saw the nvidia shader fix for Rambo and  I put the budgieloader with NVIDIA card.

**Comment by stevecrow85** [comment]
The problem with Rambo has been solved. Mission accomplished !!! I installed all packages, including Nvidia Fix Shader and in game sttings I put like the video (of couse I had to open the loader with dedicated graphic card Nividia Geforce GTX 1050, It doesn't work the integrated one Intel (R) HD Graphics 630. Thank you! https://youtu.be/HUCM3ZbDSeI
