### ISSUE TITLE
Let's Go Safari Wrong region (Fixed)

### ISSUE THREAD

**Issue by Trymado** [teknogods/teknoparrot-issues#103]
Please fill in the following information when creating a new issue:

**TeknoParrot version**: 1.0.0.299
**Did this issue happen with an older version**: no
**Game with issue**: yes
**Detailed description of issue**: Make Dongle and PCB Region to "USA", not "Export"

      <FieldName>DongleRegion</FieldName>
      <FieldValue>USA</FieldValue>
      <FieldName>PcbRegion</FieldName>
      <FieldValue>USA</FieldValue>

**Comment by Nezarn** [comment]
fixed
