### ISSUE TITLE
Homura for NesicaxLive

### ISSUE THREAD

**Issue by ghost** [teknogods/teknoparrot-issues#104]
i use the last version of teknoparrot ant when i launche this game , the game run very fast not a good speed 
i have windows 10 1909 , nvidia gforce gtx745 , 6go of memory
and when i use this game form windows 8.1 it s ok

**Comment by Nezarn** [comment]
Not a Teknoparrot\Openparrot issue, you need to limit your framerate via gpu driver or RTSS. (lazy gamedevs didn't add framelimit.)
