### ISSUE TITLE
Initial D Arcade Stage Zero Game Processes have terminated

### ISSUE THREAD

**Issue by bobwarpath123** [teknogods/teknoparrot-issues#111]
Please fill in the following information when creating a new issue:
**I AM NOT INSTALLING IN C DRIVE**
**TeknoParrot version**:
**Did this issue happen with an older version**:
**Game with issue**: Initial D Arcade Stage Zero
**Detailed description of issue**: When starting the game with all prerequisites, The command line simply gives: CreateRemoteThread failed: 80070005
                    CreateRemoteThread failed: 80070005
                  Game processes have terminated
                   Press any key to continue . . .
**Reproduction details**: Issue happens every time
**Any other details**:
![issue](https://user-images.githubusercontent.com/63062145/78268459-721b6a00-74c5-11ea-923b-bb240bfe1737.PNG)

**Pictures of issue**: Above^

UPDATE: When Ran as Administrator, I get a new error:
![Inject error](https://user-images.githubusercontent.com/63062145/78268851-0a195380-74c6-11ea-8a21-3d77cc99e621.PNG)

**Comment by nzgamer41** [comment]
Can you give this another go launching through TP with the new version? I noticed you're not actually launching it through TeknoParrot in your first screenshot (this is only for TeknoParrot related issues, IDZ generic issues should be directed to djhackers/segatools team, not us) so if the issue persists using TP then I'd love to know.
