### ISSUE TITLE
not possible to play directly to Daemon Bride 

### ISSUE THREAD

**Issue by ghost** [teknogods/teknoparrot-issues#114]
it s not possible to play Daemon Bride

**TeknoParrot version**: 1.0.0.323
**Did this issue happen with an older version**:
**Game with issue**:Daemon Bride
**Detailed description of issue**:when i have the menu it s not possible to play , the start bouton no work
**Reproduction details**:
**Any other details**: if i launch Arcana Heart 3 - Love Max Six Stars!!!!!! for NesicaxLive after if i launch Daemon Bride it s ok to play but it s not possible to play to Sega rally 3
**Pictures of issue**:

**Comment by Nezarn** [comment]
game works fine with proper dump

edit: is it the exboard version or the nesica that doesn't work?

**Comment by Nezarn** [comment]
Tested both version, they work, you most likely have a bad dump
