### ISSUE TITLE
Outrun2sp White screen with last update

### ISSUE THREAD

**Issue by Trymado** [teknogods/teknoparrot-issues#116]
Please fill in the following information when creating a new issue:

**TeknoParrot version**: 1.0.0.328
**Did this issue happen with an older version**: no
**Detailed description of issue**: the game launch with White screen. Tester with jennyfer and jennyfer_patched same issues
**Reproduction details**: juste launch the game

**Comment by Nezarn** [comment]
not an issue, as soon as build bot comes online and builds 1.0.0.168 (or newer) it will work
