### ISSUE TITLE
Gti club 3 freezes on test screen

### ISSUE THREAD

**Issue by ghost** [teknogods/teknoparrot-issues#117]
Please fill in the following information when creating a new issue:

**TeknoParrot version**:From 1.0.040 to present
**Did this issue happen with an older version**:Verified from 1.0.0.40 on
**Game with issue**: Gti club 3
**Detailed description of issue**:Game freezes on first screen (board test)
**Reproduction details**:Start the game windowed or fullscreen. The test screen appears with "Main board: OK", but it doesn't get through al other tests and suspensive points don't move.
**Any other details**:If you start the gti3.exe without Teknoparrot, it goes through all the tests but they fail as expected. The modified "exe" from another "loader" loads the game without issue.
System: Windows 7 X64, Amd 7990HD, sounblaster Z sound Card, 32GB ram.
**Pictures of issue**:

**Comment by Nezarn** [comment]
game works fine, you need to use "gti3japkey.exe"

**Comment by ghost** [comment]
Hi Nezarn. Already using gti3japkey.exe. The problem is still there. Maybe it's just my system. Thanks in any case
