### ISSUE TITLE
MarioKart GP DX OpenParrotLoader window never closes

### ISSUE THREAD

**Issue by lorenzolamas** [teknogods/teknoparrot-issues#118]
**TeknoParrot version**: 1.0.0.0.330
**Did this issue happen with an older version**: Same with the previous version 
**Game with issue**: no
**Detailed description of issue**: After closing the game MarioKart GP DX, only one DOS window (_OpenParrotLoader.exe_) never close.
**Reproduction details**: no problem with Luigi Mansion, but i don't know if it use the same methode to work
**Any other details**:
**Pictures of issue**:
![picturemessage_311j0rqo vcc](https://user-images.githubusercontent.com/9819802/80282289-edf98280-8710-11ea-8cd9-ab61cfdd1a70.png)

**Comment by Nezarn** [comment]
Should be fixed in TP Core 1.0.0.187 or newer
