### ISSUE TITLE
InitialD Arcade Stage Zero RealGearShift

### ISSUE THREAD

**Issue by you981** [teknogods/teknoparrot-issues#121]
Hshift cannot be set with InitalD ZERO.
It doesn't work if the RealGearShift item is turned on or off.
I've been using Tekunoparrot for a week or so and it hasn't worked since my version. Does anyone know a solution?

**TeknoParrot version**:1.0.0.334
Win10

**Comment by nzgamer41** [comment]
@you981 can you please upload your IDZ.xml from UserProfiles so I can take a look?

**Comment by you981** [comment]
Hi.
Thanks for your reply!
Now, when I try again, Tekno Parrot has been upgraded. And when I tried it,
Hshft worked fine. Thank you very much.

However, ID4 ~ 8 still has a problem. ID4 and ID5 cannot be started when
RealGear Shift is checked. I uncheck it and it starts up, but I can't use
Hshift. With ID6 ~ 8, the game starts even if RealGearShift is checked, but
Hshift does not work. Is there a solution for this?


[UserProfiles.zip](https://github.com/teknogods/teknoparrot-issues/files/4546882/UserProfiles.zip)

**Comment by you981** [comment]
However, Hshft does not work with or without RealGearShift checked. Shift
up and Shift down work with or without RealGearShift checked.
This is the same for ID6 ~ 8.

With ID ZERO, I can use Hshift by checking RealGearShift. When I uncheck
it, Shift up and Down can be used.

Hshft works fine on Wangan Midnight.

2020年4月28日(火) 23:25 Yuichi Nagahira <you.rx450h@gmail.com>:

**Comment by you981** [comment]
I tested TP 1.0.0342.
ID4 and ID5 can start.
 However, Hshft does not work with or without RealGearShift checked. Shift up and Shift down work with or without RealGearShift checked.
This is the same for ID6 ~ 8.

With ID ZERO, I can use Hshift by checking RealGearShift. When I uncheck it, Shift up and Down can be used.

Hshft works fine on Wangan Midnight.

**Comment by you981** [comment]
By the way, in the version about a week ago, Hshift worked even with IDs 4-8. At that time, Hshift, Shift up, and Shift down were working at the same time.
