### ISSUE TITLE
Unimplemented Sound API

### ISSUE THREAD

**Issue by LOLGuy2222** [teknogods/teknoparrot-issues#124]
Please fill in the following information when creating a new issue:

**Teknoparrot Version**:1.0.0.277
**Did this issue happen with an older version**: Probably not
**Game with issue**: The House of the Dead 4
**Detailed description of issue**: Unimplemented sound API
**Reproduction details**:  dunno what are u talking
**Any other details**: Other emulators just work fine and before, this issue never happened
**Pictures of issue**: ![image](https://user-images.githubusercontent.com/47497874/80721974-7329d080-8b31-11ea-80ce-ced0a946fb31.png)

**Comment by Nezarn** [comment]
user error, install https://www.microsoft.com/en-us/download/details.aspx?id=35 + https://www.techpowerup.com/download/visual-c-redistributable-runtime-package-all-in-one/

**Comment by LOLGuy2222** [comment]
oh thank god
:D
