### ISSUE TITLE
KOF 13 crash runtimes + game.exe when you insert coin

### ISSUE THREAD

**Issue by Trymado** [teknogods/teknoparrot-issues#125]
Please fill in the following information when creating a new issue:

**TeknoParrot version**: 1.0.0.366
**Did this issue happen with an older version**:  work on .361
**Game with issue**:  no error with previous version .361 for example
**Detailed description of issue**: The Runtimes + game.exe crash when you insert coin in the game
**Reproduction details**: launch the game and insert coin

**Pictures of issue**: 
![Capture](https://user-images.githubusercontent.com/57376909/81494946-f0311480-92ac-11ea-8bc4-8fa970227b4d.PNG)

**Comment by adamgp** [comment]
I second this - pre version 366 coin in worked without crashing. Also entering the test/service menu to switch language causes a runtime error.

**Comment by Nezarn** [comment]
works fine here, you guys should stop using modified exes

**Comment by adamgp** [comment]
Trying to... annoyingly the Internet is riddled with them and takes issues such as this to identify that it has been tampered. Thanks.

**Comment by Trymado** [comment]
I use a original exe and same problem :/

**Comment by Nezarn** [comment]
@Trymado do you have a D: drive?

**Comment by Trymado** [comment]
Yes,  my frontend (Hyperspin) is in D drive.
Games TP  is in I drive.
( I have 5 hard drive on my pc)

On previous version the game work perfectly, the problem is come only in .366

**Comment by Nezarn** [comment]
update to latest openparrot, if it still crashes you have a bad dump
