### ISSUE TITLE
KOF XIII, KOF XIII Climax attract issues

### ISSUE THREAD

**Issue by adamgp** [teknogods/teknoparrot-issues#126]
**TeknoParrot version**: 366
**Did this issue happen with an older version**: Yes
**Game with issue**: KOF XIII, KOF XIII Climax
**Detailed description of issue**: KOF XIII attract pulls you out of fullscreen and shows the video in a second window (see below image). This also causes a loss of focus for coin in to end the video. The user must switch back to the primary KOF XIII window, coin in and then attract window closes. The current version causes this to crash, however previous versions used to return this primary window to fullscreen and then the game continues as normal. If you coin in before the attract runs everything is fine. On KOF XII Climax the attract attempting to play causes an immediate crash.
**Reproduction details**: Do not insert coin when instructed and wait for attract video to play (5-10 second wait)
**Any other details**: Fullscreen mode, FullHD desktop resolution.
**Pictures of issue**:
![image](https://user-images.githubusercontent.com/2965239/81494941-7eed6380-92a4-11ea-8371-8c620b5425a5.png)

**Comment by Nezarn** [comment]
works fine here, maybe its conflicting with sega rally 3 fix?

**Comment by Trymado** [comment]
I run on Win 7, another users (win 7/10) have same problem.
When you insert coin (and only at the moment when insert coin) game crash

**Comment by Nezarn** [comment]
codec issue, tried even in a win7 VM, it worked perfectly like on my PC
