### ISSUE TITLE
Initial D 6, 7, 8 and Zero crashes when launching

### ISSUE THREAD

**Issue by camborambo** [teknogods/teknoparrot-issues#129]
Please fill in the following information when creating a new issue:

**TeknoParrot version**: 1.0.0.393
**Did this issue happen with an older version**: First time using with 1.0.0.393
**Game with issue**: Initial D 6, 7, 8 and Zero
**Detailed description of issue**: The game stop responding within 5-10 seconds after loading. I've tried troubleshooting and it seems to be graphics related. All versions are behaving in the same manner and I have to force end task. I've got the games running on other lower speced PCs without any issues. Other games games ran fine and intial D 4 & 5. 

Update: 
**Reproduction details**: 
**Any other details**:
CPU: i9-9900k
GPU: 2080 SUPER RTX with latest drivers
RAM: 32GB
**Pictures of issue**: ![Capture](https://user-images.githubusercontent.com/35091153/85463985-c5ed9a80-b56c-11ea-9f5f-5d2b4f362943.JPG)

**Comment by camborambo** [comment]
I just installed on another system with exact specs as mine and it runs fine. There must be some software conflict going on.

**Comment by Nezarn** [comment]
It is an user error then, not a TeknoParrot issue, join TeknoParrot discord and ask help there from others.

Or try the typical troubleshooting, install vc redist (all in one), dxwebsetup, reinstall or roll back to earlier GPU driver.

**Comment by norm-gd** [comment]
i was searching for initial d anime, funny how i got here
