### ISSUE TITLE
Star Trek Voyager crashes after 1st level

### ISSUE THREAD

**Issue by legend800** [teknogods/teknoparrot-issues#131]
After killing the first boss (yellow alien), you get to select 1/3 scenarios. Choosing any of them causes TP to crash. 

Tried toggling all settings - no change. 
Not sure if this worked before. 
Several others on Discord have confirmed the same. 

Let me know what else I can provide. 

Config:
Windows 10 64-bit
GeForce GTX 1080
i7-6700k @ 4GHZ
16GB RAM

**Comment by Harmmmm** [comment]
Should be fixed now!
Please test and report back :)
