### ISSUE TITLE
Persona 4 The Ultimate in Mayonaka Arena fullscreen break

### ISSUE THREAD

**Issue by Trymado** [teknogods/teknoparrot-issues#132]
Please fill in the following information when creating a new issue:

**TeknoParrot version**:1.0.0.402
**Did this issue happen with an older version**: no
**Game with issue**: no
**Detailed description of issue**: When the fullscreen is on, only windowed white windows appear
**Reproduction details**: just launch the game in fullscreen
![Capture](https://user-images.githubusercontent.com/57376909/90557621-0cd9c400-e19b-11ea-8d68-506ff7ebf820.JPG)

**Pictures of issue**:

**Comment by Nezarn** [comment]
Works fine for me on latest TP, you either have a bad dump, or you monitor doesn't support the resolution the game wants.
