### ISSUE TITLE
Ghost Squad Evolution Evo not executable.

### ISSUE THREAD

**Issue by ZiggyKun** [teknogods/teknoparrot-issues#139]
**TeknoParrot version**:1.0.0.512
**Did this issue happen with an older version**:
**Game with issue**:
**Detailed description of issue**:Ghost Squad Evolution RingEdge version is not executable.
**Reproduction details**:
**Any other details**:
**Pictures of issue**:

**Comment by ZiggyKun** [comment]
> Please fill in the 
> 
> **TeknoParrot version**:1.0.0.5.1.2
> **Did this issue happen with an older version**:
> **Game with issue**:
> **Detailed description of issue**:Ghost Squad Revolution RingEdge version is not executable.
> **Reproduction details**:
> **Any other details**:
> **Pictures of issue**:

**Comment by Nezarn** [comment]
Ghost Squad Evolution is a linux (lindbergh) game, starts with the file named vsg
