### ISSUE TITLE
DIRTY DRIVING INPUT ISSUE

### ISSUE THREAD

**Issue by EmuAl** [teknogods/teknoparrot-issues#142]
Please fill in the following information when creating a new issue:

**TeknoParrot version**: ALL
**Did this issue happen with an older version**: YES
**Game with issue**: DIRTY DRIVIN'
**Detailed description of issue**: INPUT ON MENU SELECTION IS BUGGERED, I CAN'T SELECT ANYTHING CLOSE TO THE STARTING POINT OF THE MIDDLE OF THE SCREEN
**Reproduction details**: HAPPENS EVERY TIME FOR ME
**Any other details**; HAPPENS ON TRACK, CAR, UPGRADE SELECTION AND NAME INPUT
**Pictures of issue**: https://streamable.com/qs1gg1

**Comment by EmuAl** [comment]
So Boomslangnz has fixed the track selection for this game, thanks dude.
There is still a problem with selecting cars and upgrades that are close to the middle of the screen, when i choose left or right it jumps past the first selection. Also name input is not able to pick all the letters, it jumps past several when pushing left and right on letter selection screens.

**Comment by Boomslangnz** [comment]
is this fixed yet?

**Comment by EmuAl** [comment]
Not as far as I'm aware, the issue still remains on upgrades and name selection screen but I haven't tried in a while but also haven't seen any fixes mentioned anywhere recently.

**Comment by Boomslangnz** [comment]
Ok should of fixed name selection now but upgrades seemed ok to me. I didnt see it jumping selections

**Comment by EmuAl** [comment]
I can't check this just now dude, no pc at the mo, but thanks again for looking at it. When my new pc comes, I'll  check it out.

**Comment by nugarp** [comment]
FYI it is fixed. Name and symbols are both selectable. Issue should be closed IMO.

**Comment by EmuAl** [comment]
@sm32x the upgrade screen works good for you too ?
If all screens work good the yes issue should be closed, i just can't check right now, that's all.

**Comment by nugarp** [comment]
Good point. Since I tried the game (around a week or two ago) I didn't have any issues with the upgrade screen. Last week Boomslang pushed some changes to fix the name selection after I also messaged him about it. You may need to check the upgrade screen for you but it was fine for me. I'm using a Logitech Driving Force GT.

**Comment by EmuAl** [comment]
I use a direct input controller, so will have to check when my pc arrives if it's changed for me. Cheers again for the comments and @Boomslangnz for looking again at the issues with input on this game.

**Comment by nugarp** [comment]
Ah yeah the sensitivities on a controller are likely much more aggressive near the center of the stick. I know exactly what you're talking about. I'll leave you be the ultimate decision maker for whether this is fixed!

**Comment by EmuAl** [comment]
Just checked this and it seems fine now, i can pick any option on any screen :) cheers Boomslangnz for sorting this issue.
