### ISSUE TITLE
**game with issue** Virtua fighter 5: downloaded tekno parrot multiple times, with and without antivirus, and each time virtua fighter 5(both version c and b)were gone from the exe list. as in when i tried to launch them it told me that the exe was not found.

### ISSUE THREAD

**Issue by Tipsy77l** [teknogods/teknoparrot-issues#144]
Please fill in the following information when creating a new issue:

**TeknoParrot version**: 1.0.0.140
**Did this issue happen with an older version**: no
**Game with issue**: Virtua fighter 5(both versions)
**Detailed description of issue**: When attempting to open a virtua fighter game im told that the game exe was not found
**Reproduction details**:
**Any other details**: Tried both versions, downloaded and re downloaded{teknoparrot} with and without antivirus
**Pictures of issue**:

**Comment by Nezarn** [comment]
Teknoparrot doesn't include game files.
