### ISSUE TITLE
Street fighter 5 arcade

### ISSUE THREAD

**Issue by ghost** [teknogods/teknoparrot-issues#147]
Please fill in the following information when creating a new issue:

**TeknoParrot version**:1.0.0.406
**Did this issue happen with an older version**:
**Game with issue**:street fighter 5 arcade
**Detailed description of issue**: when you dead after the count arrive to 0 , you see game over and nothing no go to the menu
**Reproduction details**:
**Any other details**:
**Pictures of issue**:

**Comment by EmiMidnight** [comment]
Fixed.
