### ISSUE TITLE
Initial D 8 eror issue

### ISSUE THREAD

**Issue by ShiroTakenshi** [teknogods/teknoparrot-issues#165]
Please fill in the following information when creating a new issue:

**1.0.0.665**:
**Did this issue happen with an older version**: NO
**Game with issue**: Yes error failed to run 
**Detailed description of issue**: Failed to run and error code :(
**Reproduction details**:
**Any other details**: When play game got an issue
**Pictures of issue**:
![image](https://user-images.githubusercontent.com/46504288/143052553-7f8199ed-2934-43e1-bdaf-612c570e0329.png)
![image](https://user-images.githubusercontent.com/46504288/143052657-61e2dcf7-a03d-44ba-aec0-f160a53915e1.png)

**Comment by Nezarn** [comment]
Bad dump or missing redist.
https://teknogods.github.io/getstarted.html
