### ISSUE TITLE
having a problem trying to use my Patreon Key

### ISSUE THREAD

**Issue by rasterico** [teknogods/teknoparrot-issues#168]
trying to enter my Patreon Key into the TPUI,  version 1.0.0.684 and keep getting this error. any help appreciated thanks.

![image](https://user-images.githubusercontent.com/13873242/147855731-54b1cf92-4ace-4ea5-bc58-ca30c04dce33.png)

**Comment by rasterico** [comment]
No idea how or why but it suddenly worked after hours of trying! Perseverance paid off I guess!

**Comment by Trymado** [comment]
so, close your issues, thanks ;)

**Comment by rasterico** [comment]
sorry, had no option to do that from Mobile browser, done now :)
