### ISSUE TITLE
Teknoparrot Exception Error When Escaping Out Of Every .xml Game Running On TP 

### ISSUE THREAD

**Issue by cnells2000** [teknogods/teknoparrot-issues#178]
**Ver. 1.0.0.766
**Yes happened with older versions up for about 6months of updates now
**cars, batman, star wars Bp, mach storm,storm racer g,gti club 3 (All games i have running with .xml instead of .bat (About 20)
**After im done playing the game and i press exit to leave the game i get the image submitted.
**No Other Details
**Picture submitted

Please fill in the following information when creating a new issue:

**TeknoParrot version**:
**Did this issue happen with an older version**:
**Game with issue**:
**Detailed description of issue**:
**Reproduction details**:
**Any other details**:
**Pictures of issue**
![Error tp](https://user-images.githubusercontent.com/90527461/172673810-163c442c-3322-4800-baea-d5b9e9fadb76.jpg)
:

**Comment by evileyecheese** [comment]
im getting the exact same error about 80 % of the time when closing games using a Taito type x3 pc and teknoparrot is updated to 1.0.0.803

**Comment by spaelectronics** [comment]
I have the same issues with the latest TP release. 
Only when running from command line.

**Comment by Alexarcade** [comment]
I added Teknoparrot in the Attrackmode frontend and I get this message when I exit the game and go back to the frontend.

**Comment by spaelectronics** [comment]
I'm using AttractMode as well, and get this error a lot.

**Comment by Alexarcade** [comment]
Using the Teknoparrot launcher when exiting the game the error message is not displayed, it happens when using the Attrackmode, rocketlauncher, bigbox frontend.

**Comment by Joecade** [comment]
I can confirm (22JAN2023), Teknoparrot (fully updated) displays this error when exiting from any game back to the CoinOPS N2 frontend.

The error is not present when using Teknoparrot by itself (no frontend).

Thank you for all your dedication to this project 👍![image](https://user-images.githubusercontent.com/123279287/213909569-4c879d4b-ec3d-4380-9a2f-b6ce394aadfc.jpeg)

**Comment by EmiMidnight** [comment]
Fixed in newer versions.
