### ISSUE TITLE
Sega Racing Classic - Test Menu Settings Won't Save

### ISSUE THREAD

**Issue by dgrace13** [teknogods/teknoparrot-issues#182]
Please fill in the following information when creating a new issue:

**TeknoParrot version**: All
**Did this issue happen with an older version**: Unknown
**Game with issue**: Sega Racing Classic
**Detailed description of issue**: Test menu settings won't save. If you want to play in LAN mode, you have to launch game, then go into test menu, set master/sub, then exit, then game should sync up. But when you exit and reload game, test menu reverts back to default settings (ie. single mode).  Thank you
**Reproduction details**:
**Any other details**:
**Pictures of issue**:

**Comment by cor094** [comment]
It will only save if you set pcb/dongle to Japan
