### ISSUE TITLE
Street Fighter V - keyboard mapping

### ISSUE THREAD

**Issue by Ragnarok9975** [teknogods/teknoparrot-issues#185]
**TeknoParrot version**: 1.0.0.937

**Did this issue happen with an older version**: don't know

**Game with issue**:Street Fighter V

**Detailed description of issue**: When trying to map keyboards keys, some inputs are conflicting with in-game hardcoded inputs ( a (on an azerty keyboard, may be q on a qwerty), s,d, arrows, etc...) - These built-in inputs should be inhibited so that only teknoparrot configured keys are used. Strangely, these keys do nothing in test mode, only in-game.

**Reproduction details**: map keys for P1 coin, start, button 1 and nothing else,  you'll be able to move with a,s,d keys on caracter selection and in-game

**Comment by EmiMidnight** [comment]
Fixed in newer versions. :)
