### ISSUE TITLE
bootstrapper crashes after update check

### ISSUE THREAD

**Issue by fstarred** [teknogods/teknoparrot-issues#190]
**TeknoParrot version**: TeknoParrot Installer Version: 1.0.0.13 31/03/2023 00:00:00
**Did this issue happen with an older version**: Don't know
**Game with issue**: N/D
**Detailed description of issue**: When Bootstrapper starts, it crashes after a few secondows without displaying any message
**Reproduction details**: N/D
**Any other details**: N/D
**Pictures of issue**: N/D

**Comment by nzgamer41** [comment]
Known issue, fix will be coming tonight.

**Comment by nzgamer41** [comment]
Fixed in https://github.com/nzgamer41/TPBootstrapper/releases/tag/1.0.0.14, update your TPBootstrapper and it will no longer crash.
