### ISSUE TITLE
Mario and Sonic at Rio - black screen

### ISSUE THREAD

**Issue by d8thstar** [teknogods/teknoparrot-issues#199]
Please fill in the following information when creating a new issue:

**TeknoParrot version**: most current (sorry not at my mcahine but i stay updated)
**Did this issue happen with an older version**: no, game worked before
**Game with issue**: Mario and Sonic at Rio
**Detailed description of issue**: game loads to black screen
**Reproduction details**: every time
**Any other details**:
**Pictures of issue**:

**Comment by GaussTek** [comment]
Same issue here, hopefully it gets fixed in future updates :(

**Comment by EmiMidnight** [comment]
This was/should have been fixed a few months earlier. Can you confirm if it works for you now?

**Comment by GaussTek** [comment]
> This was/should have been fixed a few months earlier. Can you confirm if it works for you now?

Hello! Yes, I can confirm that this works perfectly as of latest version, including custom resolution. Sorry I couldn't post here that it was fixed before.

Thanks a bunch for all the hard work!!

**Comment by EmiMidnight** [comment]
Thanks for confirming. :)
