### ISSUE TITLE
Melty Blood "start" button

### ISSUE THREAD

**Issue by ShedrockN4** [teknogods/teknoparrot-issues#2]
Please fill in the following information when creating a new issue:

**TeknoParrot version**: 1.05
**Did this issue happen with an older version**: yes
**Game with issue**: Melty Blood Actress Again Current Code
**Detailed description of issue**: "start" button does not work
**Reproduction details**: Well you just can't play and you can't push "start"
**Any other details**:
**Pictures of issue**:

**Comment by ReaverTeknoGods** [comment]
Please add controller used...

**Comment by ShedrockN4** [comment]
I tried with 2 controllers. The Logitech Rumble Pad 2 USB and the Logitech F710 Wireless Gamepad.

**Comment by ShedrockN4** [comment]
Melty Blood is 1.07 version

**Comment by avail** [comment]
are you using the new loader method? and if so, are you running dumbjvscmd for the game?

**Comment by ShedrockN4** [comment]
No. Old one.
