### ISSUE TITLE
Wangan Midnight Tune 6 Registering DLL Error

### ISSUE THREAD

**Issue by DeLuXe3** [teknogods/teknoparrot-issues#205]
I need help to fix this i dont know which DLL should i fix
![Screenshot (159)](https://github.com/teknogods/teknoparrot-issues/assets/142711039/58de88ed-9f2a-44fb-979c-641320ce02a7)

**Comment by nzgamer41** [comment]
run teknoparrot as administrator

**Comment by DeLuXe3** [comment]
yea but the problem is when i run it on administrator it will like quit when the 2 cmd prompt show up wmm6 doesnt open only 2 cmd prompt its ok if theres no other way to fix
