### ISSUE TITLE
The House of the Dead EX Test/Service Mode Crash

### ISSUE THREAD

**Issue by EllimistArcade** [teknogods/teknoparrot-issues#206]
Please fill in the following information when creating a new issue:

**TeknoParrot version**: 1.0.0.1073 Windows 10
**Did this issue happen with an older version**: Unknown
**Game with issue**: The House of the Dead EX
**Detailed description of issue**: After setting the Test button to F2 and the Service button to F3, when attempting to get into the Test menu the game crashes. Start the game, wait for it to boot up, then hit F2. Game will crash.
**Reproduction details**:Start the game, wait for it to boot up, then hit Test button. Game will crash.
**Any other details**: None
**Pictures of issue**:

**Comment by Nezarn** [comment]
This game has toggle for test mode in TeknoParrotUI, you can't go to test mode with test button.
