### ISSUE TITLE
Far Cry Paradise Lost - P1 Trigger does not work

### ISSUE THREAD

**Issue by Lorenzinio** [teknogods/teknoparrot-issues#221]
**TeknoParrot version**: 1.0.0.1190
**Did this issue happen with an older version**: yes
**Game with issue**: Far Cry Paradise Lost
**Detailed description of issue**: Player 1 trigger does not work if keyboard is set to French (France) language on windows. Starting with UK/US Keyboard resolve the problem. Then when ingame, keyboard could be changed switch back to French (France) without issue.
**Reproduction details**: Set keyboard to French (France) in Windows parameters and launch the game.
**Any other details**: Each kind of input is affected, raw, dinput and xinput.
**Pictures of issue**:

**Comment by Boomslangnz** [comment]
Thanks for this and very sorry its taken so long to actually notice this. I have just pushed fix

Will need to update to latest TeknoParrot

**Comment by Lorenzinio** [comment]
Thank you for this fix and all the work you do👍
