### ISSUE TITLE
Densha De Go direct controller position support

### ISSUE THREAD

**Issue by Prurite** [teknogods/teknoparrot-issues#253]
Please fill in the following information when creating a new issue:

**TeknoParrot version**: 1.0.0.2438
**Did this issue happen with an older version**: Yes
**Game with issue**: Densha De Go!!
**Detailed description of issue**:
The game Densha De Go arcade (train driving game) has an accelerator handle to control the power/brakes on cabinets, which tells the game its position through a combination of sensors. 
Currently teknoparrot emulates it by using 2 keys to shift between adjacent positions; I wonder if it's possible to add the option to directly input the position to the game, maybe even just expose the emulated sensors as is on the cabinets.
So with a helper script I can use my train controllers in an exact way, instead of controller -script→ arrow key -teknoparrot→ game
Which is problematic because the controller may get out of sync of the position in game.
**Reproduction details**:
**Any other details**:
**Pictures of issue**:

**Comment by jaoxford** [comment]
I saw the use of a plugin in this video:

https://www.bilibili.com/video/BV1Lx4y1J7ut/

I think that uses VJOY. 

I've also seen this plugin which maps the Zuiki controller to older DDG games: https://autotraintas.hariko.com/

**Comment by EmiMidnight** [comment]
I added button mappings for every single speed (including neutral) now. I hope that's useful, I am not sure what kind of mapping the actual switch/ps4 controller has.

**Comment by Prurite** [comment]
> I added button mappings for every single speed (including neutral) now. I hope that's useful, I am not sure what kind of mapping the actual switch/ps4 controller has.

Thanks for you effort. The actual switch controller maps the accelarator speed levels to positions on the Y joystick axis. This is my script to use it in previous versions of teknoparrot. https://gist.github.com/Prurite/9d650961319a2adb0cf42db08386d8da

**Comment by jaoxford** [comment]
> > I added button mappings for every single speed (including neutral) now. I hope that's useful, I am not sure what kind of mapping the actual switch/ps4 controller has.
> 
> Thanks for you effort. The actual switch controller maps the accelarator speed levels to positions on the Y joystick axis. This is my script to use it in previous versions of teknoparrot. https://gist.github.com/Prurite/9d650961319a2adb0cf42db08386d8da

I wonder if there's a way of setting a percentage of the analogue stick being pressed, into a button input?

**Comment by Prurite** [comment]
> I wonder if there's a way of setting a percentage of the analogue stick being pressed, into a button input?

Here is the new script https://gist.github.com/Prurite/496d02319e84f4f7acac7eeeafd431d8

**Comment by jaoxford** [comment]
> > I wonder if there's a way of setting a percentage of the analogue stick being pressed, into a button input?
> 
> Here is the new script https://gist.github.com/Prurite/496d02319e84f4f7acac7eeeafd431d8

Legend, thanks.

Will give this a spin!
