### ISSUE TITLE
GTI Club Supermini Festa Japanese Version

### ISSUE THREAD

**Issue by jf980000** [teknogods/teknoparrot-issues#254]
forgive me what i ve done to me

**Comment by jf980000** [comment]
but we need help right here

**Comment by jf980000** [comment]
anyone here

**Comment by Boomslangnz** [comment]
what are you asking exactly?

**Comment by jf980000** [comment]
we need support for new games

**Comment by Ennahh-76** [comment]
that just a reply of madness.  No specifics, no questions, no response.
