### ISSUE TITLE
Wangan Midnight Maximum Tune 5 stuck at "Connecting to Wangan Terminal, please wait..." on boot.

### ISSUE THREAD

**Issue by mladidy** [teknogods/teknoparrot-issues#27]
**TeknoParrot version**: 1.41
**Did this issue happen with an older version**: Only release the emulator supports
**Game with issue**: Wangan Midnight Maximum Tune 5
**Detailed description of issue**: Whenever I boot up Wangan Midnight Maximum Tune 5, the game just won't initialise and is now stuck at "Connecting to Wangan Terminal, please wait...", even when I have TerminalEmulator checked. Instead of just heading to attract mode it just hangs on that screen. If someone can help me fix it that would be great.
**Reproduction details**: Game just won't start it self for some reason, runs on Namco System ES3.
**Any other details**:
**Pictures of issue**:
![screenshot 83](https://user-images.githubusercontent.com/30188537/37132588-5a54df00-22c9-11e8-8a88-c06f6ff15f66.png)

**Comment by mladidy** [comment]
Never mind guys it's solved because I updated my Ethernet Network Adapter Drivers. Alright, I'm going to close up this issue. See you later guys!

**Comment by pussyslayer624** [comment]
mine is doing the same bro but im on a laptop, im on teknoparrot 1.0.0.323, it worked yesterday

**Comment by Poliwrath** [comment]
user issue

**Comment by Ofker** [comment]
> Never mind guys it's solved because I updated my Ethernet Network Adapter Drivers. Alright, I'm going to close up this issue. See you later guys!

Could you please show me where you updated the drivers for your Ethernet network adapter?
