### ISSUE TITLE
Sega Sonic pull left

### ISSUE THREAD

**Issue by ShedrockN4** [teknogods/teknoparrot-issues#3]
Please fill in the following information when creating a new issue:

**TeknoParrot version**: 1.05
**Did this issue happen with an older version**: Yes
**Game with issue**: Sega Sonic All-Stars Racing
**Detailed description of issue**: Cars tends to go on left
**Reproduction details**: Just try to go straight forward, and the car will not really go straight forward but a littlebit on left
**Any other details**: Tried with/without  Stooz Driving Improvement
**Pictures of issue**:

**Comment by ReaverTeknoGods** [comment]
Calibrating your wheel from TEST menu solves this issue.

**Comment by ShedrockN4** [comment]
Tried too. I centered it using the test menu. Same. But it seems that some people have the same problem and others don't.  So don't really know where it comes from. Tried using 2 controllers (1 on usb and one wireless).
