### ISSUE TITLE
Crashing When Opening WMMT5

### ISSUE THREAD

**Issue by lukkyducky** [teknogods/teknoparrot-issues#30]
Please fill in the following information when creating a new issue:

**TeknoParrot version**: 1.41e
**Did this issue happen with an older version**: No
**Game with issue**: WMMT5
**Detailed description of issue**: When opening WMMT5 the game will open and crash before loading into main screen. 
**Reproduction details**: Using TP 1.41e open WMMT5. Crashing occurs regardless of drivers, game version and OS version.
**Any other details**:
**Windows crash report:**
Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	wmn5r.exe
  Application Version:	0.0.0.0
  Application Timestamp:	52ce66d1
  Fault Module Name:	wmn5r.exe
  Fault Module Version:	0.0.0.0
  Fault Module Timestamp:	52ce66d1
  Exception Code:	c0000005
  Exception Offset:	0000000000909dba
  OS Version:	6.3.9600.2.0.0.768.101
  Locale ID:	1033
  Additional Information 1:	70f9
  Additional Information 2:	70f931aeb9efc42b7f6eb52b91345c54
  Additional Information 3:	beda
  Additional Information 4:	beda5edff64399214bb54bf5759eead0
**Pictures of issue**:

**Comment by Tuitaro** [comment]
![unknown](https://user-images.githubusercontent.com/36973187/37794442-5522fc02-2e76-11e8-8b61-ac73b00d4045.png)

**Comment by lukkyducky** [comment]
System specs per developer request:
Intel Xeon 2.93GHz
NVIDIA GeForce GTX 960 2GB
16GB RAM
Windows 8.1
Current version of C++ and DirectX 12.

**Comment by avail** [comment]
Caused by using base version of the game
