### ISSUE TITLE
An error in Visual C++ in Teknoparrot 1.43

### ISSUE THREAD

**Issue by knightfoxdota123** [teknogods/teknoparrot-issues#35]
Please fill in the following information when creating a new issue:

**TeknoParrot version**: 1.43
**Did this issue happen with an older version**: No , it was fine in 1.42
**Game with issue**: Wangan Midnight 5
**Detailed description of issue**: It shows some error content during starting the game
**Reproduction details**:
**Any other details**: try to fix it asap
**Pictures of issue**: 
![screenshot 243](https://user-images.githubusercontent.com/38852569/39419547-06102960-4c93-11e8-95cb-e37b03f852f7.png)

**Comment by lukkyducky** [comment]
This looks similar to when I added a bad .lua file to my data_jp > scene folder. Try getting rid of the English translations file and see if it loads

**Comment by knightfoxdota123** [comment]
Maybe there is a software problem ? it couldn't be a folder problem or a downloaded things

**Comment by derole123** [comment]
You need update 5 for it to work. You will need to find it on the internet.

**Comment by knightfoxdota123** [comment]
link pls ?? i can't find anything

**Comment by knightfoxdota123** [comment]
what ?
