### ISSUE TITLE
ID4 framerate issues

### ISSUE THREAD

**Issue by jon360x** [teknogods/teknoparrot-issues#37]
Please fill in the following information when creating a new issue:

**TeknoParrot version**:1.52c
**Did this issue happen with an older version**: Game is newly supported so no.
**Game with issue**: ID4
**Detailed description of issue**: It seems like ID4 runs over 60fps which causes certain UI animations like "TIME EXTENDED" to be sped up even the sound. Replays/Attract screen gameplay is also sped up. Some experience players also report that the framerate is affecting the handling. They aren't able to do the same actions on a wheel in the arcade without turning 180 degrees. Which makes me assume the framerate also speeds up the handling.
**Reproduction details**:
**Any other details**:
**Pictures of issue**:

**Comment by avail** [comment]
Force VSync? It's the same across all the ID games...

**Comment by jon360x** [comment]
I've enabled vsync on nvidia control panel for "Global Settings"  and its still happens.

**Comment by Nezarn** [comment]
@avail literally 0 things can hook into D4, not even driver can force stuff on it.
