### ISSUE TITLE
Guilty Gear XX Accent Core Plus R with TP 1.53 HF Controls 

### ISSUE THREAD

**Issue by fire0128** [teknogods/teknoparrot-issues#40]
Please fill in the following information when creating a new issue:

**TeknoParrot version**: 1.53 Hot Fix
**Did this issue happen with an older version**: N/A
**Game with issue**: Guilty Gear XX Accent Core Plus R
**Detailed description of issue**: 5th button for player 1 and 2 not configurable 

Guilty gear xx accent core plus R, in the teknoparrot config, is only 5 buttons, but in the game button 6 is for dust ), so is impossible to use that button at the moment
MISSING BUTTON:

in the user profile open the GXX.xml and search

"<ButtonName> Player 1 Button 5 </ ButtonName>" 
now change the next line

<InputMapping> P1Button5 </ InputMapping>

for

<InputMapping> P1Button6 </ InputMapping>

 save the setting and now you can use the button 5 mapping on Player 1 only
I found it not in userprofile not game profile folder

**Reproduction details**:
**Any other details**:
**Pictures of issue**:

**Comment by ReaverTeknoGods** [comment]
Fixed
