### ISSUE TITLE
ID4 Lindbergh Full Screen

### ISSUE THREAD

**Issue by fire0128** [teknogods/teknoparrot-issues#41]
Please fill in the following information when creating a new issue:

**TeknoParrot version**: 1.53 Hot Fix
**Did this issue happen with an older version**: N/A
**Game with issue**: Initial D 4 Export
**Detailed description of issue**:
The Game stays windowed no matter what you do, If you change your desktop resolution to 1360 x 768 the game displays fullscreen. Could this pleased be made automatic so that Teknoparrot changes desktop resolution when the game starts and changes back on exit please or some other fix to make it full screen. Many thanks for all of the work you guys do on this software

**Reproduction details**:
**Any other details**:
**Pictures of issue**:

**Comment by Nezarn** [comment]
Works fine on latest TP (you can even change the game's resolution from the UI)
