### ISSUE TITLE
Operation Ghost Full Screen

### ISSUE THREAD

**Issue by fire0128** [teknogods/teknoparrot-issues#42]
Please fill in the following information when creating a new issue:

**TeknoParrot version**: 1.53 Hot Fix
**Did this issue happen with an older version**: Yes on all versions as far as I can make out
**Game with issue**: Operation Ghost
**Detailed description of issue**:
The Game will not Display full screen, always windowed. 
**Reproduction details**:
**Any other details**:
**Pictures of issue**:

**Comment by ReaverTeknoGods** [comment]
Discord fixes-channel has work around.
