### ISSUE TITLE
Outrun 2 Lindbergh

### ISSUE THREAD

**Issue by fire0128** [teknogods/teknoparrot-issues#44]
Please fill in the following information when creating a new issue:

**TeknoParrot version**: 1.53 Hot Fix
**Did this issue happen with an older version**: Yes
**Game with issue**: Outrun 2
**Detailed description of issue**:
Textures missing, Black areas on road signs Roads and paths. Also missing textures from trees in forest level etc, be great if you could fix these, many thanks
**Reproduction details**:
**Any other details**:
**Pictures of issue**:

**Comment by ReaverTeknoGods** [comment]
Fixed
