### ISSUE TITLE
Virtua Tennis 4 framerate locked at 45 fps

### ISSUE THREAD

**Issue by gustavodandolo** [teknogods/teknoparrot-issues#45]
Please fill in the following information when creating a new issue:

**TeknoParrot version**:1.60B
**Did this issue happen with an older version**:Yes
**Game with issue**:Virtua Tennis 4
**Detailed description of issue**:Game with framerate locked at 45 fps that causes microstuttering.
**Reproduction details**:
**Any other details**:
**Pictures of issue**:

**Comment by gustavodandolo** [comment]
For example the 1.32 public version does not have this problem, framerate at 60 fps, I don't know the last Teknoparrot version without this framerate issue.

**Comment by gustavodandolo** [comment]
This problem is still unsolved.

**Comment by gustavodandolo** [comment]
Still unsolved.

**Comment by gustavodandolo** [comment]
Still unsolved.

**Comment by ReaverTeknoGods** [comment]
Fixed since some time ago since 2 player mode was introduced back.
