### ISSUE TITLE
Mario Kart DX server connection issue

### ISSUE THREAD

**Issue by Nezarn** [teknogods/teknoparrot-issues#46]
**TeknoParrot version**: 1.60B
**Did this issue happen with an older version**: no
**Game with issue**: Mario Kart DX
**Detailed description of issue**:  sometimes game gets connection timeout when using banapass
**Reproduction details**: run the game, and mostly likely the first time you "insert" your banapass, game goes offline (connection timeout?)
**Any other details**: According to tracert, there are multiple points where it timeouts
**Pictures of issue**:
![cmd_2018-08-08_09-04-34](https://user-images.githubusercontent.com/3817985/43821930-c391fd24-9aea-11e8-8c36-b7d7a00117e4.png)

**Comment by emuline** [comment]
yes sometimes banapass screen freeze because he doesn't find the save on server... +1

**Comment by legend800** [comment]
Same here
