### ISSUE TITLE
Mario Kart DX saving fails with certain karts

### ISSUE THREAD

**Issue by Nezarn** [teknogods/teknoparrot-issues#47]
**TeknoParrot version**: 1.60B
**Did this issue happen with an older version**: yes (ever since theres banapass support)
**Game with issue**: Mario Kart DX
**Detailed description of issue**: when unlocking certain type of karts, game will fail at saving (and throws the game offline)
**Reproduction details**: collect mario coins, and roll a kart that causes the issue
**Any other details**: so far I've confirmed at least 3 karts where game fails to save
**Pictures of issue**:
![unknown](https://user-images.githubusercontent.com/3817985/43822019-23d9484a-9aeb-11e8-81e4-095a113e09c7.png)

**Comment by avail** [comment]
@Nezarn this shit

**Comment by fire0128** [comment]
Yep this describes the issue well mate

**Comment by ReaverTeknoGods** [comment]
Fixed
