### ISSUE TITLE
Outrun Lidbergh

### ISSUE THREAD

**Issue by rullo30** [teknogods/teknoparrot-issues#52]
Please fill in the following information when creating a new issue:

**TeknoParrot version**: 1.65
**Did this issue happen with an older version**: no
**Game with issue**: Outrun
**Detailed description of issue**: not working at lauching
**Reproduction details**:
**Any other details**:
**Pictures of issue**:

**Comment by genuro** [comment]
+1 Yeah I just noticed this, patched elf or not. teknoparrot just closes with no error
