### ISSUE TITLE
Afterburner Climax Controls not working 100% (Xinput)

### ISSUE THREAD

**Issue by genuro** [teknogods/teknoparrot-issues#53]
Please fill in the following information when creating a new issue:

**TeknoParrot version**:1.65
**Did this issue happen with an older version**:yes
**Game with issue**:Afterburner Climax
**Detailed description of issue**:Controls 9 times out of 10 will always pull to the right even after calibrating
**Reproduction details**:it will happen at some point when running the game 3 or 4 times in a row
**Any other details**: this only seems to be an issue with XINPUT
**Pictures of issue**:

**Comment by hotgraphics** [comment]
To get around this issue, before you run the game, turn off the analog button on your controller, run the game & when at the jet selection screen turn on the analog button, no longer only steers to the right.

**Comment by ReaverTeknoGods** [comment]
Fixed
