### ISSUE TITLE
InitialD 5 crash while reading card

### ISSUE THREAD

**Issue by qiangqiang101** [teknogods/teknoparrot-issues#55]
Please fill in the following information when creating a new issue:

**TeknoParrot version**: 1.80
**Did this issue happen with an older version**: Yes
**Game with issue**: InitialD 5
**Detailed description of issue**: crash to desktop while reading card
**Reproduction details**:
**Any other details**: 
**Pictures of issue**:

**Comment by ReaverTeknoGods** [comment]
Fixed
