### ISSUE TITLE
Chase HQ 2 writes files to d:\

### ISSUE THREAD

**Issue by sialivi** [teknogods/teknoparrot-issues#57]
**TeknoParrot version**: 1.90
**Did this issue happen with an older version**: Yes
**Game with issue**: Chase HQ 2
**Detailed description of issue**:
Chase HQ 2 writes a number of ranking related files to an unwanted location, the root of the D: drive. The files in question are...
-  D:\rtc.dat
-  D:\ranking0.bin
-  D:\ranking1.bin
-  D:\rtb.dat

**Reproduction details**: Start the game and then check D:\\

**Comment by ReaverTeknoGods** [comment]
The project is open source, community should fix it.

**Comment by sialivi** [comment]
I was under the impression that teknoparrot-issues was the place to report issues, even if it falls under the "community should fix it" category, considering the issues section of OpenParrot is completely empty.

**Comment by ReaverTeknoGods** [comment]
This is NOT TeknoParrot issue, Chase HQ is part of OpenParrot.
