### ISSUE TITLE
Virtua Fighter 5 Ver. B Export creates directories in a relative path from the roms

### ISSUE THREAD

**Issue by sialivi** [teknogods/teknoparrot-issues#58]
**TeknoParrot version**: 1.90
**Did this issue happen with an older version**: Yes
**Game with issue**: Virtua Fighter 5 Ver. B Export
**Detailed description of issue**:
VF5B creates several nested directories, home\disk2\ram, in a relative path from the game roms. Not sure if any files are written to these directories later, but they were empty in my very brief test.

Here's the rompath I used:
&nbsp;&nbsp;&nbsp;&nbsp;K:\Emu\Arcade\Roms\Sega Lindbergh\Virtua Fighter 5 Ver. B Export

And this is where the directories were created:
&nbsp;&nbsp;&nbsp;&nbsp;K:\Emu\Arcade\\**home\disk2\ram**

**Reproduction details**: Start the game and check the parent directories.

**Comment by ReaverTeknoGods** [comment]
Fixed
