### ISSUE TITLE
After Burner Climax up & down not reversed whether selecting Y+ or Y-

### ISSUE THREAD

**Issue by hotgraphics** [teknogods/teknoparrot-issues#59]
TeknoParrot 1.0.0.125
It has been like this in all versions of TeknoParrot
After Burner Climax
In TeknoParrotUI, when you set up the controls under Controller Setup, under Joystick Analog Y, you press up on the joystick you get Y- and down you get Y+, now ingame when you play, it doesn't make any difference if you've chosen Y+ or Y-, either way, up on the joystick is up & down on the joystick is down, surely they should be reversed from one another depending which one you've chosen, so down can be up & up can be down if you prefer it that way?. If this is the way it's supposed to be it doesn't make sense how it is by default in TeknoParrot, in a real jet up on the joystick would make the jet go downwards & down, upwards, like it is in After Burner II in Mame.
Can be reproduced using above explanation

**Comment by adamgp** [comment]
Should this also affect Mach Storm where you can inverse the Y axis, pulling down should aim up.
Perhaps a checkbox to "Reverse Y Axis" on plane games?

**Comment by hotgraphics** [comment]
Yep, that'd do the trick.

**Comment by ReaverTeknoGods** [comment]
This is solved.
