### ISSUE TITLE
[Suggestion] Ability to Map Keyboard buttons as well as XInput controls

### ISSUE THREAD

**Issue by adamgp** [teknogods/teknoparrot-issues#60]
**TeknoParrot version**: 1.0.224
**Did this issue happen with an older version**: Unknown
**Game with issue**: All
**Detailed description of issue**: It does not appear possible to map keyboard keys to any controls for any games as well as Xinput buttons.
**Reproduction details**: Attempt to map keys for a game with Xinput checked and setting F1 to the service/test control.
**Any other details**: Ideally it would be beneficial to map (standard) keyboard keys for miscellaneous service/test controls that you wouldn't want anyone to activate on a joypad accidentally whilst discovering the keys for themself. Example; Mach Storm - where the test button takes you to the test menu and then closes the game, but has to be mapped to the JoyPad.
**Pictures of issue**:

Thanks

**Comment by ReaverTeknoGods** [comment]
No
