### ISSUE TITLE
Sega Rally 3 

### ISSUE THREAD

**Issue by Fearhasnocure** [teknogods/teknoparrot-issues#62]
Hey guys sega rally 3 no longer works anymore! it gets to the load up screen then game stops. I have tired multiple diff teknoparrot version including the newest and still same issue. im running windows 10 with no updates. I have cancelled the updates beause i know there was an issue with this game and the latest windows 10 updates. Is anyone else having this issue?

**Comment by ReaverTeknoGods** [comment]
Windows related issue.
