### ISSUE TITLE
Mouse for gun games in full screen mode

### ISSUE THREAD

**Issue by EmuAl** [teknogods/teknoparrot-issues#64]
Please fill in the following information when creating a new issue:

**TeknoParrot version**: Most of them
**Did this issue happen with an older version**: yes
**Game with issue**: mouse for gun games
**Detailed description of issue**: mouse doesn't work for gun games in full screen but does if you start windowed then quit and start full screen
**Reproduction details**: just start a mouse for gun game in full screen 
**Any other details**: been broken on and off for a long time 
**Pictures of issue**: no pictures needed

**Comment by legend800** [comment]
I can confirm this issue is still active as of 1.0.192.

**Comment by Nezarn** [comment]
I'm pretty sure this was fixed, pls retest

**Comment by nzgamer41** [comment]
pretty sure this was fixed already, can be reopened if not
