### ISSUE TITLE
[Suggestion] Ability to play Chase HQ2 & Wacky Races in LAN/Network mode

### ISSUE THREAD

**Issue by dgrace13** [teknogods/teknoparrot-issues#66]
Please fill in the following information when creating a new issue:

**TeknoParrot version**: 193
**Did this issue happen with an older version**: Yes
**Game with issue**: Chase HQ2 & Wacky Races
**Detailed description of issue**: Supposedly it is possible with jconfig and a bunch of other tweaks and hexing the IP addres, etc, but I have not had success getting these two games to work in LAN mode. Would be super nice to have that option via TP. Thank you
**Reproduction details**:
**Any other details**:
**Pictures of issue**:

**Comment by ReaverTeknoGods** [comment]
This works fine with Direct Play.
