### ISSUE TITLE
Virtua fighter 5 c

### ISSUE THREAD

**Issue by Grabisoft** [teknogods/teknoparrot-issues#68]
Please fill in the following information when creating a new issue:

**TeknoParrot version**:
As of June 26 2019

**Detailed description of issue**:
The game works fine for the most part specially after applying the shader fix. The thing is that once you get into the final fight you get all kind of weird graphic anomalies. The stage that corrupts graphics is the final one that has buildings with shinny mirrors 

**Pictures of issue**
https://cdn.discordapp.com/attachments/401150264377212928/593077642417274883/123.png

**Comment by ReaverTeknoGods** [comment]
This is shader issue, not TP issue.
