### ISSUE TITLE
Trouble running most games 

### ISSUE THREAD

**Issue by jsaviour84** [teknogods/teknoparrot-issues#7]
Please fill in the following information when creating a new issue:

**TeknoParrot version**:
**Did this issue happen with an older version**:
**Game with issue**:
**Detailed description of issue**:
**Reproduction details**:
**Any other details**:
**Pictures of issue**:

**Comment by jsaviour84** [comment]
So started off using 1.04a and id6 works fine. I tried to use any other game (src,sr3, pretty much all the other games) and they dont run. The command line loads and says the game is resuming but the game never shows up. I recently dled 1.06a and now nothing loads. Command line starts then goes away. Also Src also keeps asking to install and it uses adobe flash which no longer works on win10.. I dont know if this has to do with registry? I tried to use my current code but it said it was bad. So those are the issues im having. Any help would be great

**Comment by jsaviour84** [comment]
Why was this closed with no answer

**Comment by spazzy89** [comment]
It was probably closed because you didn't actually fill out the details in your original post. Look at all of the blank fields.

Also, Src doesn't use flash...I'm not sure you ran the actual game versus some kind of malware?
