### ISSUE TITLE
The house of the dead 4 issue

### ISSUE THREAD

**Issue by masterogi** [teknogods/teknoparrot-issues#73]
Please fill in the following information when creating a new issue:

**TeknoParrot version**:  1.0.0.201
**Did this issue happen with an older version**:  Idk
**Game with issue**:  The House of the Dead 4
**Detailed description of issue**:  I set up a key (1 or enter) as the start button, but in game it doesn't work (The game keeps showing the intro video with the tutorial and "Press Start")
**Reproduction details**:  i'll leave two images with the settings i'm currently using
**Any other details**: --
**Pictures of issue**:
![Screenshot (49)](https://user-images.githubusercontent.com/53430239/62041309-9ff43480-b1fb-11e9-8cd7-fcf9f76668a7.png)
![Screenshot (48)](https://user-images.githubusercontent.com/53430239/62041310-9ff43480-b1fb-11e9-80da-ad1d05202859.png)

**Comment by Harmmmm** [comment]
Should be fixed in current version, feel free to create a new ticket if you still have problems.

**Comment by gindev77** [comment]
Hello there!
This issue is coming back each time we update to a new version of TP.
The only option for us, is to launch the game one time windowed. then it's ok.
but i repeat : this issue come back after each new version of TP.
thanks.
