### ISSUE TITLE
Fast And Furious Super Bikes / Fast and Furious Super Bikes 2 CRC error 

### ISSUE THREAD

**Issue by ssphaneuf** [teknogods/teknoparrot-issues#76]
Please fill in the following information when creating a new issue:

**TeknoParrot version**: 1.0.0.226
**Did this issue happen with an older version**: No
**Game with issue**: Fast And Furious Super bikes / Fast And Furious Super bikes 2
**Detailed description of issue**: Game boots to a black screen with text saying "checking files" *** Fail *** CRC FILE NOT FOUND  Done checking files.... 
**Reproduction details**: Tried on 3 seperate computers and only could get it working on 1 computer. all on windows 10
**Any other details**: I'm using the same dump on 3 different computers.  I'm getting this error on 2 of the 3 computers. Game was working a couple of updates ago, but i decided to delete tp and start fresh. I'm using an older version of windows 10 on my main computer and my 2 other computers are on the current version of windows 10.
**Pictures of issue**: First picture is FNFSB. 
![fnfsb_crcerror](https://user-images.githubusercontent.com/18563921/67419114-ed750900-f580-11e9-96a0-2f6e8ec8fcda.png)

Second Picture is FNFSB2
![FNFSB2_crcerror](https://user-images.githubusercontent.com/18563921/67419306-565c8100-f581-11e9-8628-c895fe82be0a.png)

**Comment by ssphaneuf** [comment]
Figured it out

**Comment by ninjakxx** [comment]
ssphaneuf how did you figure it out?

**Comment by mukesh786** [comment]
i have same issiue can u guide me

**Comment by Zmansk88** [comment]
> Figured it out

I have the exact same error. What did you do to fix this issue??
