### ISSUE TITLE
Pokemon Tournament Controls broken

### ISSUE THREAD

**Issue by Trymado** [teknogods/teknoparrot-issues#77]
Please fill in the following information when creating a new issue:

**TeknoParrot version**: 1.0.0.230
**Did this issue happen with an older version**: no
**Game with issue**:  yes
**Detailed description of issue**: With latest Teknoparrot, controls in Pokemon Tournament doesn't work. But with older Teknoparrot ( for example 1.92) the controller setup work perfectly.

**Comment by Poliwrath** [comment]
Please try the latest version.

**Comment by Trymado** [comment]
work fine with latest version ! Thanks a lot
