### ISSUE TITLE
Ultra Street Fighter IV : Test mode doesn't save changes

### ISSUE THREAD

**Issue by rufotheone-fr** [teknogods/teknoparrot-issues#85]
Please fill in the following information when creating a new issue:

**TeknoParrot version**: 1.0.0.251
**Did this issue happen with an older version**: Dunno
**Game with issue**: Ultra Street Fighter IV
**Detailed description of issue**: Test mode doesn't save any change made within
**Reproduction details**: Hit the "test" button and go to Game option > Language > English + Game option > PCB select > VS Match. Exit the test mode. Relaunch the game.
**Any other details**:
**Pictures of issue**:

**Comment by rufotheone-fr** [comment]
Solved.

Game requires that a partition with letter D exists in order to save bookkeeping.

**Comment by iProfessorZ** [comment]
I have a D drive in the system, but still cant save any modification to test mode, the game will stop after exit the test mode. Dunno why.
