### ISSUE TITLE
Ikaruga Nesica Broken

### ISSUE THREAD

**Issue by Trymado** [teknogods/teknoparrot-issues#90]
Please fill in the following information when creating a new issue:

**TeknoParrot version**: 1.0.0.254
**Did this issue happen with an older version**: no
**Game with issue**: no
**Detailed description of issue**: Error News CRC with exe file (see picture)
**Pictures of is
![2019-12-06 png a3aa269f0a8ff3545852d028fa727e3c](https://user-images.githubusercontent.com/57376909/70374049-edda2100-18ee-11ea-8c36-36c6dcfa6bd7.png)
sue**:

**Comment by adamgp** [comment]
Try a different dump (exe).

**Comment by Trymado** [comment]
I tried 3 different dumps, always the same error. On the old version of TP the game is launched perfectly.

**Comment by Trymado** [comment]
Fixed with latest version, thanks a lot !
