### ISSUE TITLE
HOTD4 UseMouseForGun broken

### ISSUE THREAD

**Issue by Trymado** [teknogods/teknoparrot-issues#93]
Please fill in the following information when creating a new issue:

**TeknoParrot version**: 1.0.0.267
**Did this issue happen with an older version**: no
**Game with issue**: House of the Dead 4
**Detailed description of issue**: UseMouseForGun doesn't work in game
**Reproduction details**: Just try to launch the game
Thx

**Comment by Trymado** [comment]
Issue find, It is a bug. 
1.Put the game in windowed mode.
2.Start the game and exit.
3.Disable windowed mode and start the game

**Comment by ReaverTeknoGods** [comment]
This really should be fixed properly.

**Comment by Trymado** [comment]
Great thanks a lot !

**Comment by Harmmmm** [comment]
Should be fixed now!
Please test and report back :)

**Comment by Trymado** [comment]
Hi, work great, thanks a lot
    Le lundi 10 août 2020 à 23:16:21 UTC+2, Harm <notifications@github.com> a écrit :  
 
 


Should be fixed now!
Please test and report back :)

**Comment by Harmmmm** [comment]
Fixed.
