### ISSUE TITLE
Luigi Mansion "UseMouseForGun" doesn't work

### ISSUE THREAD

**Issue by Trymado** [teknogods/teknoparrot-issues#94]
Please fill in the following information when creating a new issue:

**TeknoParrot version**: 1.0.0.277
**Did this issue happen with an older version**: i don't now
**Detailed description of issue**: Mouse doesn't work in game, only gamepad work
**Reproduction details**: play the the game with "UseMouseForGun" option stick

**Comment by manuelx98** [comment]
Have you tried to press 1 to start the game first? Apparently, some controls are hard-coded within "UseMouseForGun" option, here the ones that I tested:
Player 1 Start - 1 (keyboard)
Player 1 Vacuum Button - Left button (mouse)
Player 1 Vacuum Lever - Right button (mouse)

**Comment by Harmmmm** [comment]
Should be fixed now!
Please test and report back :)

**Comment by Trymado** [comment]
Hi,work greatthanks

    Le lundi 10 août 2020 à 23:16:42 UTC+2, Harm <notifications@github.com> a écrit :  
 
 


Should be fixed now!
Please test and report back :)

**Comment by Harmmmm** [comment]
Fixed.
