### ISSUE TITLE
Rambo - The Arcade Game

### ISSUE THREAD

**Issue by razors78** [teknogods/teknoparrot-issues#95]
Please fill in the following information when creating a new issue:

**TeknoParrot version**:
1.0.0.277
**Did this issue happen with an older version**:
No
**Game with issue**:
Rambo (Sega)
**Detailed description of issue**:
The game crashes before or after Stage 1 is finished. And sometimes it doesn't  crash until after Stage 2. Also, the mouse cursor gets lost while the game continues playing and you get shot until Game Over. After that you can't start the game any longer and need to re-boot it again to play..
**Reproduction details**:
The issue happens every time you boot the game up, give or take.
**Any other details**:
**Pictures of issue**:

**Comment by Harmmmm** [comment]
Should be fixed in current version, feel free to create a new ticket if you still have problems.
