### ISSUE TITLE
Rambo controls mapping Issue

### ISSUE THREAD

**Issue by bojo5150** [teknogods/teknoparrot-issues#96]
Please fill in the following information when creating a new issue:

**TeknoParrot version**: 277 (latest as of 1/25/2020)
**Did this issue happen with an older version**: No but I was playing Rambo on .221 until this morning so "maybe"
**Game with issue**: Rambo
**Detailed description of issue**: Direct Input no longer working. All buttons are mapped to my keyboard. I went ahead and remapped them this morning as well (in v277) however I cannot start the game because the start button doesn't work (I have it mapped to "1" on my keyboard) As note I also have "Use mouse as gun selected"
**Reproduction details**:
**Any other details**: I did not try switching to xinput. I play on an arcade cab so I'm more or less locked into direct input keyboard mapping
**Pictures of issue**:

**Comment by Harmmmm** [comment]
Should be fixed in current version, feel free to create a new ticket if you still have problems.
