### ISSUE TITLE
Luigi's Mansion windows texture bug? 

### ISSUE THREAD

**Issue by ginzu2077** [teknogods/teknoparrot-issues#98]
Please fill in the following information when creating a new issue:

Someone who doesn't know much about ghitub, asked me to open an issue for him
Here it is:

**TeknoParrot version**: actual version : (v1.0.0.288/26)
**it appear he's got this issue as soon that the game was playable on tp
**Game with issue**:Luigi's mansion
**Detailed description of issue**:
Hello I wanted to report this bug for this game.
There are other forum members who have the same graphics bug we are on windows 7 64bits

I don't think this bug is related to Windows 7 or Windows 10 version.

On my PC, the game has already worked correctly only 2 times.

But since each launch I have the graphic bug as on the attached image (textures and graphics missing) but the game remains playable.

https://image.noelshack.com/fichiers/2020/04/6/1579907736-sans-titre.jpg

I don't know if it is possible to find a solution in Teknoparrot for this game.

Apart from this bug the game works very well
**Reproduction details**:
**Any other details**:
**Pictures of issue**:

Thanks for him

**Comment by ginzu2077** [comment]
Close

**Comment by GhostM121** [comment]
I have this issue, can you please explain why you closed it or how you fixed it?

**Comment by OancaAndrei** [comment]
@GhostM121, I had the same issue.

I've fixed it by disabling `General - Windowed` in `Game Settings` when launching from TeknoParrot UI 1.0.0.530.
