### ISSUE TITLE
Luigi's Mansion crosshair bug

### ISSUE THREAD

**Issue by ginzu2077** [teknogods/teknoparrot-issues#99]
This time, it's me who report an other bug with Luigi's Mansion. 
I play this game on windows 10.
I use wiimote like a mouse. 
I tested also with a normal mouse and this remain the same behaviour. 

**TeknoParrot version**:(v1.0.0.288/26)
**Did this issue happen with an older version**: yes
**Game with issue**:Luigi's Mansion
**Detailed description of issue**:
When pointing the crosshair against each border of the screen, the crosshair keep stick on the border for about 1 sec. 
This behaviour is non blocking but it reduce a lot the in-game entertainment. 
**Reproduction details**:
**Any other details**:
If someone could do something, it would be great. The game is good! 
**Pictures of issue**:

**Comment by Harmmmm** [comment]
Should be fixed now!
Please test and report back :)

**Comment by Harmmmm** [comment]
Should be fixed in current version, feel free to create a new ticket if you still have problems.
